import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const root = fileURLToPath(new URL('../src/components', import.meta.url))

const uiDir = path.join(root, 'ui')

const output = path.join(root, 'index.ts')

function getComponentDirs(): string[] {
  return fs
    .readdirSync(uiDir)
    .filter((dir: string) => fs.existsSync(path.join(uiDir, dir, 'index.ts')))
}

function generate(): void {
  const dirs = getComponentDirs()

  let content = `// Generated by scripts/gen-entry.ts. Do not edit manually.\n\n`

  for (const dir of dirs) {
    content += `export * from './ui/${dir}/index'\n`
  }

  fs.writeFileSync(output, content, 'utf-8')
  console.log('✨ Generated entry file at', output)
}

generate()
